AntiAliasing 0
PreSharpen 1
Bloom 1
Technicolor 1
ToneMap 1
Sepia 0
PostSharpen 1
FxaaQualityPreset 6
FxaaQualitySubpix 5
FxaaQualityEdgeThreshold 7
FxaaQualityEdgeThresholdMin 5
HighQualitySharpen 0
AverageBlur 5
CoefficientsBlur 5
SharpenEdge 5
SharpenContour 4
BloomPreset 4
BloomThreshold 4
BloomWidth 4
BloomPower 4
TechniAmount 4
TechniPower 6
RedNegativeAmount 1
GreenNegativeAmount 1
BlueNegativeAmount 1
Gamma 4
Exposure 6
Saturation 6
Bleach 3
Defog 5
SepiaPower 1
GreyPower 2
Sharpen 7
BloomPresetToggle 1
Rawumber
